"""mdlc — компилятор статичных моделей в формат Source MDL v48 (Garry's Mod) без studiomdl.

Пишет .mdl, .vvd, .dx90.vtx, .dx80.vtx, .sw.vtx и .phy (коробка-коллизия) — ту же раскладку,
что выдаёт studiomdl для статичного пропа с одной костью (сверено с эталонной моделью).

Ограничения: одна кость, одна последовательность idle, одна LOD, коллизия — ограничивающий бокс.
Для анимированных моделей и точной коллизии используйте QC + studiomdl (tools/compile_models.bat).

API:
    compile_model(out_dir, name, model_path, tris, cdmaterials, surfaceprop="default", mass=1.0)
      tris: {material_name: [[(pos(x,y,z), normal(x,y,z), uv(u,v)) x3], ...]}
            вершины в порядке «против часовой» (как в Blender/SMD).
      model_path: "nyrp/clothes/cap.mdl" (то, что пишется в заголовок).
"""
import math
import os
import struct
import zlib

IN2M = 0.0254  # дюймы Source -> метры IVP


class Buf:
    def __init__(self):
        self.b = bytearray()
        self.strings = []  # (pos, base, text)

    def tell(self):
        return len(self.b)

    def pad(self, align):
        while len(self.b) % align:
            self.b.append(0)

    def put(self, fmt, *vals):
        self.b += struct.pack("<" + fmt, *vals)

    def put_at(self, pos, fmt, *vals):
        struct.pack_into("<" + fmt, self.b, pos, *vals)

    def str_ref(self, base, text):
        """Резервирует int под смещение строки относительно base."""
        self.strings.append((self.tell(), base, text))
        self.put("i", 0)


def _vec_sub(a, b):
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def _tangent(p0, p1, p2, uv0, uv1, uv2, n):
    e1, e2 = _vec_sub(p1, p0), _vec_sub(p2, p0)
    du1, dv1 = uv1[0] - uv0[0], uv1[1] - uv0[1]
    du2, dv2 = uv2[0] - uv0[0], uv2[1] - uv0[1]
    r = du1 * dv2 - du2 * dv1
    if abs(r) < 1e-9:
        t = (1.0, 0.0, 0.0)
    else:
        r = 1.0 / r
        t = tuple((e1[i] * dv2 - e2[i] * dv1) * r for i in range(3))
    # ортогонализация к нормали
    d = sum(t[i] * n[i] for i in range(3))
    t = tuple(t[i] - n[i] * d for i in range(3))
    ln = math.sqrt(sum(c * c for c in t)) or 1.0
    return (t[0] / ln, t[1] / ln, t[2] / ln, 1.0)


def _prepare(tris):
    """Материалы -> меши с дедуплицированными вершинами и индексами (по часовой)."""
    meshes = []
    for mat, tlist in tris.items():
        verts, index, lookup = [], [], {}
        for tri in tlist:
            tri = [tri[0], tri[2], tri[1]]  # VTX хранит треугольники по часовой стрелке
            tan = _tangent(tri[0][0], tri[1][0], tri[2][0], tri[0][2], tri[1][2], tri[2][2], tri[0][1])
            for p, n, uv in tri:
                key = (tuple(round(c, 4) for c in p), tuple(round(c, 3) for c in n), (round(uv[0], 4), round(uv[1], 4)))
                if key not in lookup:
                    lookup[key] = len(verts)
                    verts.append((tuple(p), tuple(n), (uv[0], uv[1]), tan))
                index.append(lookup[key])
        if len(verts) > 65535:
            raise ValueError(f"{mat}: слишком много вершин ({len(verts)})")
        meshes.append((mat, verts, index))
    return meshes


def _bounds(meshes):
    pts = [v[0] for _, verts, _ in meshes for v in verts]
    mn = tuple(min(p[i] for p in pts) for i in range(3))
    mx = tuple(max(p[i] for p in pts) for i in range(3))
    return mn, mx


# ---------------------------------------------------------------------- MDL --

def _write_mdl(model_path, meshes, cdmaterials, surfaceprop, mass, checksum, mn, mx):
    b = Buf()
    nmesh = len(meshes)
    total_verts = sum(len(v) for _, v, _ in meshes)
    center = tuple((mn[i] + mx[i]) / 2 for i in range(3))

    # --- studiohdr_t (408) ---
    b.put("4si i", b"IDST", 48, checksum)
    b.b += model_path.encode()[:63].ljust(64, b"\0")
    b.put("i", 0)                                   # length (позже)
    b.put("3f", 0, 0, 0)                            # eyeposition
    b.put("3f", *center)                            # illumposition
    b.put("3f", *mn)                                # hull_min
    b.put("3f", *mx)                                # hull_max
    b.put("3f", 0, 0, 0)                            # view_bbmin
    b.put("3f", 0, 0, 0)                            # view_bbmax
    b.put("i", 0x1)                                 # flags: AUTOGENERATED_HITBOX
    H = b.tell()                                    # 156: начало массива счётчиков/индексов
    b.b += b"\0" * (408 - H)
    fields = ("numbones boneindex numbonecontrollers bonecontrollerindex numhitboxsets hitboxsetindex "
              "numlocalanim localanimindex numlocalseq localseqindex activitylistversion eventsindexed "
              "numtextures textureindex numcdtextures cdtextureindex numskinref numskinfamilies skinindex "
              "numbodyparts bodypartindex numlocalattachments localattachmentindex numlocalnodes localnodeindex "
              "localnodenameindex numflexdesc flexdescindex numflexcontrollers flexcontrollerindex numflexrules "
              "flexruleindex numikchains ikchainindex nummouths mouthindex numlocalposeparameters "
              "localposeparamindex surfacepropindex keyvalueindex keyvaluesize numlocalikautoplaylocks "
              "localikautoplaylockindex mass contents numincludemodels includemodelindex virtualModel "
              "szanimblocknameindex numanimblocks animblockindex animblockModel bonetablebynameindex "
              "pVertexBase pIndexBase").split()
    off = {f: H + 4 * i for i, f in enumerate(fields)}

    def hset(field, value, fmt="i"):
        b.put_at(off[field], fmt, value)

    hset("mass", float(mass), "f")
    hset("contents", 1)
    b.put_at(388, "i", 0)                           # flexcontrolleruiindex (позже)
    b.put_at(400, "i", 408)                         # studiohdr2index

    # --- studiohdr2_t (256) ---
    hdr2 = b.tell()
    b.put("i", 0)                                   # numsrcbonetransform
    b.put("i", 0)                                   # srcbonetransformindex (позже)
    b.put("i", 0)                                   # illumpositionattachmentindex
    b.put("f", 0)                                   # flMaxEyeDeflection
    b.put("i", 0)                                   # linearboneindex
    b.str_ref(hdr2, model_path)                     # sznameindex
    b.b += b"\0" * (256 - (b.tell() - hdr2))

    # --- bone ---
    bone = b.tell()
    hset("numbones", 1)
    hset("boneindex", bone)
    b.str_ref(bone, "root")
    b.put("i", -1)
    b.put("6i", *([-1] * 6))
    b.put("3f", 0, 0, 0)                            # pos
    b.put("4f", 0, 0, 0, 1)                         # quat
    b.put("3f", 0, 0, 0)                            # rot (radian euler)
    b.put("3f", *([0.0039216] * 3))                 # posscale
    b.put("3f", 1.2e-5, 1.2e-5, 4.8e-5)             # rotscale
    b.put("12f", 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0)  # poseToBone
    b.put("4f", 0, 0, 0, 0)                         # qAlignment
    b.put("i", 0x500)                               # flags: USED_BY_HITBOX | USED_BY_VERTEX_LOD0
    b.put("3i", 0, 0, 0)                            # proctype, procindex, physicsbone
    b.str_ref(bone, surfaceprop)                    # surfacepropidx
    b.put("i", 1)                                   # contents
    b.put("8i", *([0] * 8))
    hset("bonecontrollerindex", b.tell())
    hset("localattachmentindex", b.tell())

    # --- hitbox set ---
    hbs = b.tell()
    hset("numhitboxsets", 1)
    hset("hitboxsetindex", hbs)
    b.str_ref(hbs, "default")
    b.put("ii", 1, 12)
    hb = b.tell()
    b.put("ii", 0, 0)
    b.put("3f", *mn)
    b.put("3f", *mx)
    b.str_ref(hb, "")
    b.put("8i", *([0] * 8))

    # --- bonetablebyname ---
    hset("bonetablebynameindex", b.tell())
    b.put("B", 0)
    b.pad(4)

    # --- animdesc + данные анимации (одна кость, единичный кватернион) ---
    ad = b.tell()
    hset("numlocalanim", 1)
    hset("localanimindex", ad)
    b.put("i", -ad)
    b.str_ref(ad, "@idle")
    b.put("f", 30.0)
    b.put("i", 0)                                   # flags
    b.put("i", 1)                                   # numframes
    b.put("ii", 0, 0)                               # movements
    b.put("6i", *([0] * 6))
    b.put("i", 0)                                   # animblock
    animindex_pos = b.tell()
    b.put("i", 0)                                   # animindex (позже)
    b.put("9i", *([0] * 9))                         # ikrules … sectionframes, zeroframe span+count, zeroframeindex
    b.put("f", 0)                                   # zeroframestalltime
    assert b.tell() - ad == 100
    b.pad(16)
    b.put_at(animindex_pos, "i", b.tell() - ad)
    b.put("BBh", 0, 0x20, 0)                        # bone 0, STUDIO_ANIM_RAWROT2, nextoffset 0
    q = 0x100000 | (0x100000 << 21) | (0x100000 << 42)  # Quaternion64 (0,0,0,1)
    b.put("Q", q)
    b.pad(16)

    # --- seqdesc ---
    sd = b.tell()
    hset("numlocalseq", 1)
    hset("localseqindex", sd)
    b.put("i", -sd)
    b.str_ref(sd, "idle")
    b.str_ref(sd, "")                               # activity name
    b.put("iii", 0, -1, 0)                          # flags, activity, actweight
    b.put("ii", 0, 212)                             # numevents, eventindex
    b.put("3f", *mn)
    b.put("3f", *mx)
    b.put("ii", 1, 216)                             # numblends, animindexindex
    b.put("i", 0)                                   # movementindex
    b.put("2i", 1, 1)                               # groupsize
    b.put("2i", -1, -1)                             # paramindex
    b.put("2f", 0, 0)                               # paramstart
    b.put("2f", 0, 0)                               # paramend
    b.put("i", 0)                                   # paramparent
    b.put("2f", 0.2, 0.2)                           # fade in/out
    b.put("3i", 0, 0, 0)                            # localentrynode, localexitnode, nodeflags
    b.put("3f", 0, 0, 0)                            # entryphase, exitphase, lastframe
    b.put("3i", 0, 0, 0)                            # nextseq, pose, numikrules
    b.put("iii", 0, 212, 212)                       # numautolayers, autolayerindex, weightlistindex
    b.put("iii", 0, 0, 216)                         # posekeyindex, numiklocks, iklockindex
    b.put("ii", 220, 0)                             # keyvalueindex, keyvaluesize
    b.put("3i", 0, 0, 0)                            # cycleposeindex, activitymodifierindex, numactivitymodifiers
    b.put("5i", *([0] * 5))
    assert b.tell() - sd == 212
    b.put("f", 1.0)                                 # weightlist
    b.put("h", 0)                                   # animindex для blend 0
    b.pad(4)

    # --- bodypart / model / meshes ---
    bp = b.tell()
    hset("numbodyparts", 1)
    hset("bodypartindex", bp)
    hset("localnodeindex", bp)
    hset("localnodenameindex", bp)
    b.str_ref(bp, "body")
    b.put("iii", 1, 1, 16)                          # nummodels, base, modelindex
    mdl = b.tell()
    b.b += os.path.basename(model_path).replace(".mdl", ".smd").encode()[:63].ljust(64, b"\0")
    b.put("i", 0)                                   # type
    radius = max(math.sqrt(sum(c * c for c in v[0])) for _, vs, _ in meshes for v in vs)
    b.put("f", radius)                              # boundingradius
    b.put("ii", nmesh, 148)                         # nummeshes, meshindex
    b.put("iii", total_verts, 0, 0)                 # numvertices, vertexindex, tangentsindex
    b.put("ii", 0, 0)                               # attachments
    eyeball_pos = b.tell()
    b.put("ii", 0, 0)                               # numeyeballs, eyeballindex (позже)
    b.put("2i", 0, 0)                               # vertexdata
    b.put("8i", *([0] * 8))
    assert b.tell() - mdl == 148
    voff = 0
    for i, (_, verts, _) in enumerate(meshes):
        me = b.tell()
        b.put("iii", i, mdl - me, len(verts))       # material, modelindex, numvertices
        b.put("i", voff)                            # vertexoffset
        b.put("iiiii", 0, 0, 0, 0, i)               # numflexes, flexindex, materialtype, materialparam, meshid
        b.put("3f", 0, 0, 0)                        # center
        b.put("i", 0)                               # vertexdata ptr
        b.put("8i", *([len(verts)] * 8))            # numLODVertexes
        b.put("8i", *([0] * 8))
        voff += len(verts)
    after_meshes = b.tell()
    b.put_at(eyeball_pos + 4, "i", after_meshes - mdl)
    for f in ("flexdescindex", "flexcontrollerindex", "flexruleindex", "ikchainindex", "mouthindex",
              "localposeparamindex", "localikautoplaylockindex"):
        hset(f, mdl + 148)
    b.put_at(388, "i", mdl + 148)

    # --- textures ---
    tex = b.tell()
    hset("numtextures", nmesh)
    hset("textureindex", tex)
    hset("includemodelindex", tex)
    hset("animblockindex", tex)
    for mat, _, _ in meshes:
        t = b.tell()
        b.str_ref(t, mat)
        b.put("5i", 0, 0, 0, 0, 0)                  # flags, used, unused1, material, clientmaterial
        b.put("10i", *([0] * 10))
    cd = b.tell()
    hset("numcdtextures", 1)
    hset("cdtextureindex", cd)
    b.str_ref(0, cdmaterials.replace("/", "\\").rstrip("\\") + "\\")
    sk = b.tell()
    hset("numskinref", nmesh)
    hset("numskinfamilies", 1)
    hset("skinindex", sk)
    for i in range(nmesh):
        b.put("h", i)
    b.pad(4)

    # --- таблица строк ---
    st = b.tell()
    hset("keyvalueindex", st)
    hset("szanimblocknameindex", st)
    b.put_at(hdr2 + 4, "i", st)                     # srcbonetransformindex
    pool = {"": st}
    b.b += b"\0"
    for _, _, text in b.strings:
        if text not in pool:
            pool[text] = b.tell()
            b.b += text.encode() + b"\0"
    for pos, base, text in b.strings:
        b.put_at(pos, "i", pool[text] - base)
    surf = pool[surfaceprop]
    hset("surfacepropindex", surf)
    b.pad(4)
    b.put_at(76, "i", len(b.b))
    return bytes(b.b)


# ---------------------------------------------------------------------- VVD --

def _write_vvd(meshes, checksum):
    verts = [v for _, vs, _ in meshes for v in vs]
    n = len(verts)
    out = bytearray(struct.pack("<4si i i 8i i i i i", b"IDSV", 4, checksum, 1, *([n] * 8), 0, 64, 64, 64 + n * 48))
    for p, nrm, uv, _ in verts:
        out += struct.pack("<3f3BB3f3f2f", 1.0, 0.0, 0.0, 0, 0, 0, 1, *p, *nrm, *uv)
    for _, _, _, t in verts:
        out += struct.pack("<4f", *t)
    return bytes(out)


# ---------------------------------------------------------------------- VTX --

def _write_vtx(meshes, checksum, max_bones_per_strip):
    n = len(meshes)
    out = bytearray()
    out += struct.pack("<iiHHiiiiii", 7, 24, max_bones_per_strip, 9, 3, checksum, 1, 0, 1, 36)
    out += struct.pack("<ii", 1, 8)                 # bodypart: numModels, modelOffset
    out += struct.pack("<ii", 1, 8)                 # model: numLODs, lodOffset
    out += struct.pack("<iif", n, 12, 0.0)          # lod: numMeshes, meshOffset, switchPoint
    mesh0 = len(out)
    sg0 = mesh0 + 9 * n
    strip0 = sg0 + 25 * n
    vert0 = strip0 + 27 * n
    total_v = sum(len(v) for _, v, _ in meshes)
    idx0 = vert0 + 9 * total_v
    total_i = sum(len(i) for _, _, i in meshes)
    bsc0 = idx0 + 2 * total_i
    mrl = bsc0 + 8 * n

    vpos, ipos = vert0, idx0
    for k, (_, verts, index) in enumerate(meshes):
        me = mesh0 + 9 * k
        sg = sg0 + 25 * k
        sp = strip0 + 27 * k
        out += b""  # заголовки пишутся ниже через pack_into
        struct.pack_into("<iiB", _grow(out, me + 9), me, 1, sg - me, 0)
        struct.pack_into("<iiiiiiB", _grow(out, sg + 25), sg, len(verts), vpos - sg, len(index), ipos - sg, 1, sp - sg, 2)
        struct.pack_into("<iiiihBii", _grow(out, sp + 27), sp, len(index), 0, len(verts), 0, 1, 1, 1, bsc0 + 8 * k - sp)
        vpos += 9 * len(verts)
        ipos += 2 * len(index)
    _grow(out, vert0)
    for _, verts, _ in meshes:
        for i in range(len(verts)):
            out += struct.pack("<3BBH3b", 0, 1, 2, 1, i, 0, 0, 0)
    for _, _, index in meshes:
        out += struct.pack(f"<{len(index)}H", *index)
    for _ in meshes:
        out += struct.pack("<ii", 0, 0)             # bone state change: hw 0 -> bone 0
    assert len(out) == mrl
    out += struct.pack("<ii", 0, 0)                 # material replacement list (LOD 0)
    struct.pack_into("<i", out, 24, mrl)
    return bytes(out)


def _grow(buf, size):
    if len(buf) < size:
        buf += b"\0" * (size - len(buf))
    return buf


# ---------------------------------------------------------------------- PHY --
# Топология выпуклой коробки (12 треугольников) в формате IVP compact ledge.
# Точки: знаки (x, y, z) в координатах IVP.
_BOX_SIGNS = [(1, 1, -1), (-1, 1, -1), (1, 1, 1), (-1, 1, 1), (-1, -1, -1), (1, -1, -1), (1, -1, 1), (-1, -1, 1)]
_BOX_TRIS = [  # (tri_index, pierce_index, [(start_point, opposite_offset), x3])
    (0, 9, [(0, 8), (1, 3), (2, 18)]), (1, 8, [(2, -3), (1, 21), (3, 39)]),
    (2, 11, [(1, -8), (0, 3), (4, 14)]), (3, 10, [(4, -3), (0, 5), (5, 20)]),
    (4, 7, [(0, 6), (6, 15), (5, -5)]), (5, 6, [(0, -18), (2, 23), (6, -6)]),
    (6, 5, [(1, -14), (4, 3), (3, -21)]), (7, 4, [(3, -3), (4, 8), (7, 11)]),
    (8, 1, [(5, -15), (6, 5), (4, -20)]), (9, 0, [(6, 6), (7, -8), (4, -5)]),
    (10, 3, [(6, 6), (3, -11), (7, -6)]), (11, 2, [(6, -23), (2, -39), (3, -6)]),
]


def _write_phy(name, mn, mx, mass, surfaceprop, checksum):
    # Source -> IVP: x = x, y = -z, z = y (в метрах)
    cx, cy, cz = ((mn[0] + mx[0]) / 2) * IN2M, -((mn[2] + mx[2]) / 2) * IN2M, ((mn[1] + mx[1]) / 2) * IN2M
    hx = max((mx[0] - mn[0]) / 2, 0.25) * IN2M
    hy = max((mx[2] - mn[2]) / 2, 0.25) * IN2M
    hz = max((mx[1] - mn[1]) / 2, 0.25) * IN2M
    radius = math.sqrt(hx * hx + hy * hy + hz * hz)
    a, b_, c = 2 * hx, 2 * hy, 2 * hz
    inertia = ((b_ * b_ + c * c) / 12, (a * a + c * c) / 12, (a * a + b_ * b_) / 12)

    ledge = bytearray()
    ledge += struct.pack("<iiIhh", 16 + 12 * 16, 0, (21 << 8) | 0x4, 12, 0)
    for ti, pierce, edges in _BOX_TRIS:
        ledge += struct.pack("<I", ti | (pierce << 12))
        for sp, opp in edges:
            ledge += struct.pack("<I", (sp & 0xFFFF) | ((opp & 0x7FFF) << 16))
    for sx, sy, sz in _BOX_SIGNS:
        ledge += struct.pack("<3fi", cx + sx * hx, cy + sy * hy, cz + sz * hz, 0)
    assert len(ledge) == 336

    surf_size = 48 + 336 + 28
    cs = bytearray()
    cs += struct.pack("<3f3ff", cx, cy, cz, *inertia, radius)
    cs += struct.pack("<I", 250 | (surf_size << 8))
    cs += struct.pack("<i", 48 + 336)               # offset_ledgetree_root
    cs += struct.pack("<3i", 0, 0, 0)
    struct.pack_into("<4s", cs, 44, b"IVPS")
    cs += ledge
    sizes = [min(255, math.ceil(h / radius * 250)) for h in (hx, hy, hz)]
    cs += struct.pack("<ii4f3Bb", 0, -336, cx, cy, cz, radius, *sizes, 0)
    assert len(cs) == surf_size

    solid = struct.pack("<4sHHi3fi", b"VPHY", 0x100, 0, surf_size, 1.0, 1.0, 1.0, 0) + bytes(cs)
    volume = (2 * hx / IN2M) * (2 * hy / IN2M) * (2 * hz / IN2M)
    text = (f'solid {{\n"index" "0"\n"name" "{name}_phys"\n"mass" "{mass:.6f}"\n"surfaceprop" "{surfaceprop}"\n'
            f'"damping" "0.000000"\n"rotdamping" "0.000000"\n"inertia" "1.000000"\n"volume" "{volume:.6f}"\n}}\n'
            f'editparams {{\n"rootname" ""\n"totalmass" "{mass:.6f}"\n}}\n').encode() + b"\0"
    return struct.pack("<iiii", 16, 0, 1, checksum) + struct.pack("<i", len(solid)) + solid + text


# ------------------------------------------------------------------- public --

def compile_model(out_dir, name, model_path, tris, cdmaterials, surfaceprop="default", mass=1.0):
    meshes = _prepare(tris)
    mn, mx = _bounds(meshes)
    checksum = zlib.crc32(repr((model_path, mn, mx, sum(len(i) for _, _, i in meshes))).encode()) & 0x7FFFFFFF
    os.makedirs(out_dir, exist_ok=True)
    base = os.path.join(out_dir, name)
    with open(base + ".mdl", "wb") as f:
        f.write(_write_mdl(model_path, meshes, cdmaterials, surfaceprop, mass, checksum, mn, mx))
    with open(base + ".vvd", "wb") as f:
        f.write(_write_vvd(meshes, checksum))
    vtx90 = _write_vtx(meshes, checksum, 53)
    for ext, data in ((".dx90.vtx", vtx90), (".dx80.vtx", _write_vtx(meshes, checksum, 16)), (".sw.vtx", vtx90)):
        with open(base + ext, "wb") as f:
            f.write(data)
    with open(base + ".phy", "wb") as f:
        f.write(_write_phy(name, mn, mx, mass, surfaceprop, checksum))
    return mn, mx
