JOB.Name = "Уборщик улиц"
JOB.Description = "По району раскиданы мешки с мусором — соберите их (E). Платят за каждый мешок."
JOB.Icon = "j_trash"
JOB.Color = Color(120, 180, 90)
JOB.Type = "collect"
JOB.Pay = 12                      -- за каждый предмет
JOB.Count = 6                     -- сколько за заход
JOB.UseTime = 3
JOB.SpotModel = "models/props_junk/garbage_bag001a.mdl"
JOB.UseText = "Собираю мусор..."
JOB.Skill = "strength"
JOB.SkillXP = 4
JOB.StationModel = "models/nyrp/city/trash_basket.mdl"
JOB.DropModel = "models/props_junk/TrashDumpster01a.mdl"   -- собранное отнести сюда
JOB.DropText = "Выбросить мешки в мусорный контейнер"
